# Generated by Django 5.2.6 on 2025-09-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full-Time"),
                    ("part-time", "Part-Time"),
                    ("contract", "Contract"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
