pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
        PYTHON = 'python3'
    }

    stages {
        stage('Clone Repo') {
        steps {
            git branch: 'main', url: 'https://github.com/jamesonJC/alx-project-nexus.git'
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                ${PYTHON} -m venv ${VENV_DIR}
                . ${VENV_DIR}/bin/activate
                pip install --upgrade pip
                pip install -r jobboard_backend/requirements.txt
                '''
            }
        }

        stage('Run Migrations') {
            steps {
                sh '''
                source ${VENV_DIR}/bin/activate
                cd jobboard_backend
                python manage.py migrate
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                source ${VENV_DIR}/bin/activate
                cd jobboard_backend
                python manage.py test
                '''
            }
        }

        // Deployment stage
        //stage('Deploy to Production') {
        //    step {
        //        sh '''
        //        echo "Deploying application..."
        //        When {
        //            branch 'main'
        //        }
        //        Steps {
        //            sh 'echo Deploying to production server...'
        //            // You can SSH into a server, or trigger Render deployment webhook
        //       '''
        //    }
        //}
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}